### ISSUE TITLE
CW 6

### ISSUE THREAD

**Issue by Yeetus-Christ** [oleksandrblazhko/ai-191-krantovskyi#18]

**Comment by Yeetus-Christ** [comment]
1. Варіант 7
Кількість таблиць - 21
Кількість користувачів - 28
Кількість груп - 14

1.1.
DAC = 28 * 21 = 588 операцій
RBAC = 28 * 14 + 21 * 14 = 686 операцій
MAC = 28 + 21 = 49 операцій
Враховуючи кількість користувачів, таблиць та ролей, переходити з DAC до RBAC недоцільно, оскільки кількість операцій збільшиться на 98. Щодо переходу з RBAC до MAC, він надасть зменшення на 637 операцій, тому цей перехід має сенс.

1.2.
Збільшимо кількість користувачів на 2. 28 * 2 = 56
DAC = 56 * 21 = 1176 операцій
RBAC = 56 * 14 + 21 * 14 = 1078 операцій
MAC = 56 + 21 = 77 операцій
Виходячи з результатів, перехід з DAC до RBAC є доцільним, оскільки при подвоєнні кількості користувачів, кількість операцій у RBAC зменшується на 98 у порівнянні з DAC. Перехад з RBAC до MAC все ще є доцільним, оскільки він зменшить кількість операцій на 1001.

**Comment by Yeetus-Christ** [comment]
2.1.
Моє програмне забезпечення з 1 лабораторної роботи обробляє наступні таблиці:
- Client (замовник)
- Order (замовлення)
- Courier (Кур'єр)
- Pizza (піца)

Користувачі мого ПЗ:
- Замовник
- Кур'єр
- Менеджер
- Кухар

Групи користувачів:
- Група замовників
- Група працівників
- Група менеджерів

2.2.
Розроблене ПЗ використовує DAC модель керування доступом. Вона реалізована за допомогою MSSQL бази даних та вибіркового надання доступу окремих ролей до окремих таблиць. Наприклад замовник може тільки зчитувати дані з таблиці Pizza, а менеджер може зчитувати, змінювати, додавати да видаляти дані з цієї таблиці.

2.3.
Збільшимо кількість користувіачів у 100 разів та розрахуємо кількість операцій для кожного модулю керування доступом.
Користувачі - 400
Таблиці - 4
Ролі - 3

DAC = 100 * 4 = 400 операцій
RBAC = 100 * 3 + 3 * 4 = 312 операцій
MAC = 100 + 4 = 104 операцій

Виходячи з результатів, було б доцільно змінити DAC модель на RBAC або MAC, для зменшення кількості операцій.

**Comment by oleksandrblazhko** [comment]
Оцінка = 5 балів
