### ISSUE TITLE
Control Work # 0

### ISSUE THREAD

**Issue by oleksandrblazhko** [oleksandrblazhko/ai-191-krantovskyi#3]
Правильна відповідь на контрольне запитання дозволить вам отримати додаткові 2 бали 
до балів за виконання лабораторної роботи, якщо ви виявите бажання надати таку відповідь.
Відповідайте на запитання через коментар.

Запитання
6) Відомо, що з серпня 2021 року GitHub-сервер забороняє клонувати Private GitHub-репозиторії 
через процедуру аутентифікації на основі паролю. Опишіть, будь ласка, 
інші два засоби безпеки, які дозволяють зробити таке клонування.

**Comment by Yeetus-Christ** [comment]
1. Клонування за допомогою SSH ключів. Потрібно згенерувати SSH ключ у налаштуваннях акаунту, і використовувати його для клонування.
2. Клонування за допомогою Personal Access Token. Потрібно згенерувати персональний ключ у налаштуваннях акаунту та зберегти його. Під час генерації можна налаштовувати доступ до репозиторію та роботи з ним.

**Comment by oleksandrblazhko** [comment]
Рішення прийнято.
Оцінка = 2 бали
